# Identification parameters
exp_name: "o2p2_pre_planning_next_state_prediction"

# Dataset and Dataloader parameters
data_root: '/home/rudra/Downloads/rudra/relationship_modeling/o2p2/physics_engine/data/initial_final'
num_files: 3  # Number of files for each of the instance in the train or validation set
max_objects: 10 # Maximum number of objects that can be present in the image, including the dropped object
img_ic: 3  # Number of channels in the input image
img_h: 64  # Height of image
img_w: 64  # Width of image
mask_ic: 1  # Number of channels in the input mask
mask_h: 64  # Height of mask
mask_w: 64  # Width of mask
num_workers: 0
use_cuda: False
batch_size: 1

# Module specific parameters
perception:
  ic: 4  # Number of channels in the input tensor to perception module
  npf: 32  # Number of out channels for the base convolution, using it's multiplicative factor
  ks: 4  # Kernel size for convolutions
  stride: 2  # Stride for convolutions
  obj_dim: 256  # Object vector dimension

render:
  oc: 3  # Number of channels in the output tensor
  mc: 1  # Number of channels in the mask
  obj_dim: 256  # Object vector dimension
  ks1: 5  # Kernel size for first two convolutions (4 convs in total)
  ks2: 6  # Kernel size for last two convolutions  (4 convs in total)
  stride: 2  # Stride for convolutions

physics-transition:
  obj_dim: 256
  hidden: 512

# Training parameters

